# Generated by Django 6.0.3 on 2026-04-04 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0026_giaodichkho_signature_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='giam_gia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='khuyen_mai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang', to='gis_store.khuyenmai', verbose_name='Voucher áp dụng'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='kinh_do_giao_hang',
            field=models.FloatField(blank=True, null=True, verbose_name='Kinh độ giao hàng'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='ma_voucher_ap_dung',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã voucher áp dụng'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='tong_tien_truoc_giam',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền trước giảm'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='vi_do_giao_hang',
            field=models.FloatField(blank=True, null=True, verbose_name='Vĩ độ giao hàng'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='dang_ap_dung',
            field=models.BooleanField(default=True, verbose_name='Đang áp dụng'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='gia_tri_don_hang_toi_thieu',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn tối thiểu'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='gia_tri_giam',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giá trị giảm'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='giam_toi_da',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Giảm tối đa'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='loai_giam',
            field=models.CharField(choices=[('fixed', 'Giảm số tiền'), ('percent', 'Giảm theo phần trăm')], default='fixed', max_length=20, verbose_name='Loại giảm giá'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='ma_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Mã voucher'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='ngay_bat_dau',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu'),
        ),
        migrations.AddField(
            model_name='khuyenmai',
            name='ngay_ket_thuc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc'),
        ),
    ]
