# Generated by Django 6.0.3 on 2026-04-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0027_donhang_giam_gia_donhang_khuyen_mai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khuyenmai',
            name='ma_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Mã voucher'),
        ),
        migrations.RunSQL(
            sql="UPDATE gis_store_khuyenmai SET ma_code = NULL WHERE ma_code = '';",
            reverse_sql="UPDATE gis_store_khuyenmai SET ma_code = '' WHERE ma_code IS NULL;",
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='ma_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Mã voucher'),
        ),
    ]
