# Generated by Django 6.0.3 on 2026-04-04 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0031_alter_donhang_phuong_thuc_thanh_toan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuahang',
            name='kinh_do',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Kinh độ (lng)'),
        ),
        migrations.AlterField(
            model_name='cuahang',
            name='vi_do',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Vĩ độ (lat)'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='kinh_do_giao_hang',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Kinh độ giao hàng'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='vi_do_giao_hang',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Vĩ độ giao hàng'),
        ),
    ]
