# Generated by Django 6.0.3 on 2026-04-04 12:41

import django.db.models.deletion
from django.db import migrations, models


def seed_store_stock(apps, schema_editor):
    GiaoDichKho = apps.get_model("gis_store", "GiaoDichKho")
    TonKhoCuaHang = apps.get_model("gis_store", "TonKhoCuaHang")
    DonHang = apps.get_model("gis_store", "DonHang")

    for movement in GiaoDichKho.objects.filter(cua_hang__isnull=True, nhan_vien__cua_hang__isnull=False):
        movement.cua_hang_id = movement.nhan_vien.cua_hang_id
        movement.save(update_fields=["cua_hang"])

    order_store_map = {}
    for movement in GiaoDichKho.objects.filter(don_hang__isnull=False, cua_hang__isnull=False).order_by("don_hang_id", "id"):
        order_store_map.setdefault(movement.don_hang_id, movement.cua_hang_id)
    for order_id, store_id in order_store_map.items():
        DonHang.objects.filter(pk=order_id, cua_hang_xu_ly__isnull=True).update(cua_hang_xu_ly_id=store_id)

    balances = {}
    movements = GiaoDichKho.objects.filter(cua_hang__isnull=False).order_by("created_at", "id")
    for movement in movements:
        key = (movement.cua_hang_id, movement.san_pham_id)
        balances.setdefault(key, 0)
        balances[key] += movement.so_luong if movement.loai == "import" else -movement.so_luong

    for (store_id, product_id), quantity in balances.items():
        TonKhoCuaHang.objects.update_or_create(
            cua_hang_id=store_id,
            san_pham_id=product_id,
            defaults={"ton_kho": max(quantity, 0)},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0032_alter_cuahang_kinh_do_alter_cuahang_vi_do_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='anh_bien_lai',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Ảnh biên lai chuyển khoản'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='cua_hang_xu_ly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang_xu_ly', to='gis_store.cuahang', verbose_name='Cửa hàng xử lý'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='ma_giao_dich_thanh_toan',
            field=models.CharField(blank=True, max_length=120, verbose_name='Mã giao dịch thanh toán'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='thoi_gian_gui_bien_lai',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian gửi biên lai'),
        ),
        migrations.AddField(
            model_name='giaodichkho',
            name='cua_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giao_dich_kho', to='gis_store.cuahang', verbose_name='Cửa hàng'),
        ),
        migrations.CreateModel(
            name='TonKhoCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton_kho', models.PositiveIntegerField(default=0, verbose_name='Tồn kho')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_kho_san_pham', to='gis_store.cuahang', verbose_name='Cửa hàng')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ton_kho_theo_cua_hang', to='gis_store.sanpham', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Tồn kho cửa hàng',
                'verbose_name_plural': 'Tồn kho cửa hàng',
                'ordering': ['cua_hang__ten', 'san_pham__ten'],
                'constraints': [models.UniqueConstraint(fields=('cua_hang', 'san_pham'), name='uniq_store_product_stock')],
            },
        ),
        migrations.RunPython(seed_store_stock, migrations.RunPython.noop),
    ]
