# Generated by Django 6.0.3 on 2026-04-04 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0033_donhang_anh_bien_lai_donhang_cua_hang_xu_ly_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XacNhanThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanh_dong', models.CharField(choices=[('submitted', 'Đã gửi biên lai'), ('approved', 'Đã duyệt biên lai'), ('rejected', 'Đã từ chối biên lai')], max_length=20, verbose_name='Hành động')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_xac_nhan_thanh_toan', to='gis_store.donhang', verbose_name='Đơn hàng')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xac_nhan_thanh_toan_da_thuc_hien', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Xác nhận thanh toán',
                'verbose_name_plural': 'Xác nhận thanh toán',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
