# Generated by Django 6.0.4 on 2026-04-13 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0037_tonkhoaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giaodichkho',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Giao dịch kho', 'verbose_name_plural': 'Giao dịch kho'},
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo'),
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giao_dich_kho_da_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='don_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giao_dich_kho', to='gis_store.donhang', verbose_name='Đơn hàng liên quan'),
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='ghi_chu',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='loai',
            field=models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho')], max_length=20, verbose_name='Loại giao dịch'),
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='san_pham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giao_dich_kho', to='gis_store.sanpham', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='so_luong',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='ton_sau',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Tồn sau'),
        ),
        migrations.AlterField(
            model_name='giaodichkho',
            name='ton_truoc',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Tồn trước'),
        ),
        migrations.AlterField(
            model_name='tonkhoaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
