# Generated by Django 5.2.8 on 2026-04-17 02:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0038_alter_giaodichkho_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhGiaCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Số sao')),
                ('binh_luan', models.TextField(blank=True, verbose_name='Bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('cua_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='gis_store.cuahang', verbose_name='Cửa hàng')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia_cua_hang', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đánh giá cửa hàng',
                'verbose_name_plural': 'Đánh giá cửa hàng',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TepDanhGiaCuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tep', models.FileField(upload_to='reviews/', verbose_name='Tệp')),
                ('loai', models.CharField(choices=[('image', 'Hình ảnh'), ('video', 'Video')], max_length=10, verbose_name='Loại tệp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('danh_gia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tep_dinh_kem', to='gis_store.danhgiacuahang', verbose_name='Đánh giá')),
            ],
            options={
                'verbose_name': 'Tệp đánh giá cửa hàng',
                'verbose_name_plural': 'Tệp đánh giá cửa hàng',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
