# Generated by Django 6.0.4 on 2026-04-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0040_diachikhachhang_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diachikhachhang',
            name='phuong_xa',
            field=models.CharField(blank=True, max_length=120, verbose_name='Khu vực'),
        ),
    ]
