# Generated by Django 6.0.4 on 2026-04-20 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0041_alter_diachikhachhang_phuong_xa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='danhgiacuahang',
            constraint=models.UniqueConstraint(fields=('user', 'cua_hang'), name='unique_user_store_review'),
        ),
    ]
