# Generated by Django 6.0.4 on 2026-05-08 08:29

import modules.store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_store', '0048_apply_checkout_voucher_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='anh_bien_lai',
            field=models.ImageField(blank=True, null=True, upload_to=modules.store.models.receipt_image_upload_to, verbose_name='Ảnh biên lai chuyển khoản'),
        ),
        migrations.AlterField(
            model_name='hinhanhsanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to=modules.store.models.product_image_upload_to, verbose_name='Ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to=modules.store.models.product_image_upload_to, verbose_name='Hình ảnh sản phẩm'),
        ),
        migrations.AlterField(
            model_name='tranggioithieu',
            name='anh_bia',
            field=models.ImageField(blank=True, null=True, upload_to=modules.store.models.about_image_upload_to, verbose_name='Ảnh bìa'),
        ),
        migrations.AlterField(
            model_name='tranggioithieu',
            name='anh_noi_dung_1',
            field=models.ImageField(blank=True, null=True, upload_to=modules.store.models.about_image_upload_to, verbose_name='Ảnh nội dung 1'),
        ),
        migrations.AlterField(
            model_name='tranggioithieu',
            name='anh_noi_dung_2',
            field=models.ImageField(blank=True, null=True, upload_to=modules.store.models.about_image_upload_to, verbose_name='Ảnh nội dung 2'),
        ),
        migrations.AlterField(
            model_name='tranggioithieu',
            name='anh_noi_dung_3',
            field=models.ImageField(blank=True, null=True, upload_to=modules.store.models.about_image_upload_to, verbose_name='Ảnh nội dung 3'),
        ),
        migrations.AlterField(
            model_name='tranggioithieuhinhanh',
            name='hinh_anh',
            field=models.ImageField(upload_to=modules.store.models.about_image_upload_to, verbose_name='Hình ảnh'),
        ),
    ]
