CREATE TABLE TUYEN (
    MATUYEN   VARCHAR2(10) PRIMARY KEY,
    BENDAU    VARCHAR2(50),
    BENCUOI   VARCHAR2(50),
    GIATUYEN  NUMBER,
    NGXB      DATE,
    TGDK      NUMBER
);

CREATE TABLE XE (
    MAXE    VARCHAR2(10) PRIMARY KEY,
    BIENKS  VARCHAR2(20),
    MATUYEN VARCHAR2(10),
    SOGHET1 NUMBER,
    SOGHET2 NUMBER,

    CONSTRAINT FK_XE_TUYEN
    FOREIGN KEY (MATUYEN)
    REFERENCES TUYEN(MATUYEN)
);

CREATE TABLE KHACH (
    MAHK     VARCHAR2(10) PRIMARY KEY,
    HOTEN    VARCHAR2(50),
    GIOITINH VARCHAR2(5),
    CMND     VARCHAR2(20)
);

CREATE TABLE VEXE (
    MATUYEN VARCHAR2(10),
    MAHK    VARCHAR2(10),
    NGMUA   DATE,
    GIAVE   NUMBER,

    CONSTRAINT PK_VEXE
    PRIMARY KEY (MATUYEN, MAHK, NGMUA),

    CONSTRAINT FK_VEXE_TUYEN
    FOREIGN KEY (MATUYEN)
    REFERENCES TUYEN(MATUYEN),

    CONSTRAINT FK_VEXE_KHACH
    FOREIGN KEY (MAHK)
    REFERENCES KHACH(MAHK)
);

ALTER TABLE TUYEN
ADD CONSTRAINT CK_TUYEN_GIA
CHECK (TGDK <= 5 OR GIATUYEN > 200000);


--------------------------------------------------
-- TRIGGER TĂNG GIÁ 20%
--------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_TANG_GIA
BEFORE INSERT OR UPDATE ON TUYEN
FOR EACH ROW
BEGIN
    IF :NEW.NGXB BETWEEN
       DATE '2016-12-29'
       AND
       DATE '2017-01-05'
    THEN
        :NEW.GIATUYEN := :NEW.GIATUYEN * 1.2;
    END IF;
END;
/
--------------------------------------------------
-- NHẬP DỮ LIỆU
--------------------------------------------------

-- TUYEN
INSERT INTO TUYEN VALUES
('T11A','SG','DL',210000,DATE '2016-12-26',6);

INSERT INTO TUYEN VALUES
('T32D','PT','SG',120000,DATE '2016-12-30',4);

INSERT INTO TUYEN VALUES
('T06F','NT','DNG',225000,DATE '2017-01-02',7);


-- XE
INSERT INTO XE VALUES
('X01','52LD-4393','T11A',20,20);

INSERT INTO XE VALUES
('X02','59LD-7247','T32D',36,36);

INSERT INTO XE VALUES
('X03','55LD-6850','T06F',15,15);


-- KHACH
INSERT INTO KHACH VALUES
('KH01','Lam Van Ben','Nam','655615896');

INSERT INTO KHACH VALUES
('KH02','Duong Thi Luc','Nu','275648642');

INSERT INTO KHACH VALUES
('KH03','Hoang Thanh Tung','Nam','456889143');


-- VEXE
INSERT INTO VEXE VALUES
('T11A','KH01',DATE '2016-12-20',210000);

INSERT INTO VEXE VALUES
('T32D','KH02',DATE '2016-12-25',144000);

INSERT INTO VEXE VALUES
('T06F','KH03',DATE '2016-12-30',270000);


COMMIT;

ALTER TABLE TUYEN
ADD CONSTRAINT CK_TUYEN_GIA
CHECK (TGDK <= 5 OR GIATUYEN > 200000);

SELECT *
FROM VEXE
WHERE EXTRACT(MONTH FROM NGMUA) = 12
ORDER BY GIAVE DESC;

SELECT MATUYEN, COUNT(*) AS SOLUONG
FROM VEXE
WHERE EXTRACT(YEAR FROM NGMUA) = 2016
GROUP BY MATUYEN
HAVING COUNT(*) = (
    SELECT MIN(COUNT(*))
    FROM VEXE
    WHERE EXTRACT(YEAR FROM NGMUA) = 2016
    GROUP BY MATUYEN
);

SELECT V.MATUYEN
FROM VEXE V
JOIN KHACH K ON V.MAHK = K.MAHK
GROUP BY V.MATUYEN
HAVING
    SUM(CASE WHEN K.GIOITINH = 'Nam' THEN 1 ELSE 0 END) > 0
AND
    SUM(CASE WHEN K.GIOITINH = 'Nu' THEN 1 ELSE 0 END) > 0;

SELECT K.MAHK, K.HOTEN
FROM KHACH K
WHERE K.GIOITINH = 'Nu'
AND NOT EXISTS (
    SELECT *
    FROM TUYEN T
    WHERE NOT EXISTS (
        SELECT *
        FROM VEXE V
        WHERE V.MATUYEN = T.MATUYEN
        AND V.MAHK = K.MAHK
    )
);

