--------------------------------------------------
-- XOA BANG
--------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SHARE_TB CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CHANNEL CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VIDEO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS_TB CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------
-- TAO BANG
--------------------------------------------------

CREATE TABLE USERS_TB (
    USER_ID     VARCHAR2(10) PRIMARY KEY,
    USERNAME    VARCHAR2(50),
    PASSWD      VARCHAR2(50),
    REGDAY      DATE DEFAULT SYSDATE,
    NATIONALITY VARCHAR2(50)
);

CREATE TABLE CHANNEL (
    CHANNELID   VARCHAR2(10) PRIMARY KEY,
    CNAME       VARCHAR2(100),
    SUBSCRIBES  NUMBER,
    OWNER_ID    VARCHAR2(10),
    CREATED     DATE,
    CONSTRAINT FK_CHANNEL_USER
        FOREIGN KEY (OWNER_ID)
        REFERENCES USERS_TB(USER_ID)
);

CREATE TABLE VIDEO (
    VIDEOID     VARCHAR2(20) PRIMARY KEY,
    TITLE       VARCHAR2(200),
    DURATION    NUMBER,
    AGE         NUMBER
);

CREATE TABLE SHARE_TB (
    VIDEOID     VARCHAR2(20),
    CHANNELID   VARCHAR2(10),
    CONSTRAINT PK_SHARE PRIMARY KEY (VIDEOID, CHANNELID),
    CONSTRAINT FK_SHARE_VIDEO
        FOREIGN KEY (VIDEOID) REFERENCES VIDEO(VIDEOID),
    CONSTRAINT FK_SHARE_CHANNEL
        FOREIGN KEY (CHANNELID) REFERENCES CHANNEL(CHANNELID)
);

--------------------------------------------------
-- TRIGGER
--------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_CHECK_DATE
BEFORE INSERT OR UPDATE ON CHANNEL
FOR EACH ROW
DECLARE
    V_REGDAY DATE;
BEGIN
    SELECT REGDAY
    INTO V_REGDAY
    FROM USERS_TB
    WHERE USER_ID = :NEW.OWNER_ID;

    IF :NEW.CREATED < V_REGDAY THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ngay tao kenh phai >= ngay dang ky');
    END IF;
END;
/

--------------------------------------------------
-- INSERT
--------------------------------------------------

INSERT INTO USERS_TB VALUES ('001','faptv','123456abc',DATE '2014-01-01','Viet Nam');
INSERT INTO USERS_TB VALUES ('002','kemxoitv','@147869iii',DATE '2015-06-05','Campuchia');
INSERT INTO USERS_TB VALUES ('003','openshare','qwertyuiop',DATE '2009-05-12','Viet Nam');

INSERT INTO CHANNEL VALUES ('C120','FAP TV',2343,'001',DATE '2014-01-02');
INSERT INTO CHANNEL VALUES ('C905','Kem xoi TV',1032,'002',DATE '2015-07-09');
INSERT INTO CHANNEL VALUES ('C357','OpenShare Cafe',5064,'003',DATE '2010-12-10');

INSERT INTO VIDEO VALUES ('V100229','FAPtv Com Nguoi Tap 41',469,18);
INSERT INTO VIDEO VALUES ('V211002','Kem xoi Tap 31',312,16);
INSERT INTO VIDEO VALUES ('V400002','Noi tinh yeu ket thuc',378,0);

INSERT INTO SHARE_TB VALUES ('V100229','C905');
INSERT INTO SHARE_TB VALUES ('V211002','C120');
INSERT INTO SHARE_TB VALUES ('V400002','C357');

COMMIT;

--------------------------------------------------
-- QUERY
--------------------------------------------------

-- 1
SELECT * FROM VIDEO WHERE AGE >= 16;

-- 2
SELECT CHANNELID, CNAME, SUBSCRIBES
FROM CHANNEL
ORDER BY SUBSCRIBES DESC
FETCH FIRST 1 ROW ONLY;

-- 3
SELECT * FROM CHANNEL;

-- 4
SELECT V.VIDEOID,
       V.TITLE,
       COUNT(S.CHANNELID) AS SO_KENH
FROM VIDEO V
LEFT JOIN SHARE_TB S
    ON V.VIDEOID = S.VIDEOID
WHERE V.AGE = 18
GROUP BY V.VIDEOID, V.TITLE;

-- 5
SELECT V.VIDEOID, V.TITLE
FROM VIDEO V
WHERE NOT EXISTS (
    SELECT 1
    FROM CHANNEL C
    WHERE NOT EXISTS (
        SELECT 1
        FROM SHARE_TB S
        WHERE S.VIDEOID = V.VIDEOID
          AND S.CHANNELID = C.CHANNELID
    )
);

