-- QUAN LY DIEM SINH VIEN
-- Da sua theo dung ten bang va ten cot trong anh mau: DMKHOA, DMMH, DMSV, KETQUA.

SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

PROMPT ===== QUAN LY DIEM SINH VIEN - DROP OLD OBJECTS =====

BEGIN EXECUTE IMMEDIATE 'DROP TABLE KETQUA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DMSV CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DMMH CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DMKHOA CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT ===== CREATE TABLES =====

CREATE TABLE DMKHOA (
    MAKHOA   CHAR(2) CONSTRAINT PK_DMKHOA PRIMARY KEY,
    TENKHOA  NVARCHAR2(30) NOT NULL
);

CREATE TABLE DMMH (
    MAMH     CHAR(2) CONSTRAINT PK_DMMH PRIMARY KEY,
    TENMH    NVARCHAR2(35) NOT NULL,
    SOTIET   NUMBER(3) NOT NULL
);

CREATE TABLE DMSV (
    MASV      CHAR(3) CONSTRAINT PK_DMSV PRIMARY KEY,
    HOSV      NVARCHAR2(30) NOT NULL,
    TENSV     NVARCHAR2(10) NOT NULL,
    PHAI      NVARCHAR2(3),
    NGAYSINH  DATE NOT NULL,
    NOISINH   NVARCHAR2(25),
    MAKH      CHAR(2) NOT NULL,
    HOCBONG   NUMBER(10,0),
    CONSTRAINT FK_DMSV_DMKHOA FOREIGN KEY (MAKH) REFERENCES DMKHOA(MAKHOA)
);

CREATE TABLE KETQUA (
    MASV      CHAR(3) NOT NULL,
    MAMH      CHAR(2) NOT NULL,
    DIEM      NUMBER(4,2) CHECK (DIEM BETWEEN 0 AND 10),
    CONSTRAINT PK_KETQUA PRIMARY KEY (MASV, MAMH),
    CONSTRAINT FK_KETQUA_DMSV FOREIGN KEY (MASV) REFERENCES DMSV(MASV),
    CONSTRAINT FK_KETQUA_DMMH FOREIGN KEY (MAMH) REFERENCES DMMH(MAMH)
);

PROMPT ===== INSERT SAMPLE DATA =====

INSERT INTO DMKHOA VALUES ('CN', N'Cong nghe thong tin');
INSERT INTO DMKHOA VALUES ('QT', N'Quan tri kinh doanh');
INSERT INTO DMKHOA VALUES ('KT', N'Ke toan');

INSERT INTO DMMH VALUES ('C1', N'Co so du lieu', 45);
INSERT INTO DMMH VALUES ('C2', N'Cau truc du lieu', 45);
INSERT INTO DMMH VALUES ('L1', N'Lap trinh huong doi tuong', 60);
INSERT INTO DMMH VALUES ('K1', N'Ke toan tai chinh', 30);
INSERT INTO DMMH VALUES ('Q1', N'Nhap mon quan tri', 30);

INSERT INTO DMSV VALUES ('001', N'Nguyen', N'An',    N'Nam', TO_DATE('12/03/2005','DD/MM/YYYY'), N'Da Nang',   'CN', 500000);
INSERT INTO DMSV VALUES ('002', N'Tran',   N'Binh',  N'Nam', TO_DATE('25/07/2005','DD/MM/YYYY'), N'Hue',       'CN', NULL);
INSERT INTO DMSV VALUES ('003', N'Le',     N'Chi',   N'Nu',  TO_DATE('09/09/2005','DD/MM/YYYY'), N'Da Nang',   'CN', 300000);
INSERT INTO DMSV VALUES ('004', N'Pham',   N'Dung',  N'Nu',  TO_DATE('01/01/2005','DD/MM/YYYY'), N'Quang Nam', 'QT', NULL);
INSERT INTO DMSV VALUES ('005', N'Vo',     N'Em',    N'Nu',  TO_DATE('18/11/2005','DD/MM/YYYY'), N'Da Nang',   'KT', 200000);
INSERT INTO DMSV VALUES ('006', N'Hoang',  N'Giang', N'Nam', TO_DATE('22/04/2005','DD/MM/YYYY'), N'Quang Tri', 'CN', NULL);
INSERT INTO DMSV VALUES ('007', N'Bui',    N'Hanh',  N'Nu',  TO_DATE('30/05/2005','DD/MM/YYYY'), N'Hue',       'QT', 400000);
INSERT INTO DMSV VALUES ('008', N'Dang',   N'Khoa',  N'Nam', TO_DATE('14/02/2005','DD/MM/YYYY'), N'Da Nang',   'KT', NULL);

INSERT INTO KETQUA VALUES ('001', 'C1', 7.7);
INSERT INTO KETQUA VALUES ('001', 'C2', 7.8);
INSERT INTO KETQUA VALUES ('001', 'L1', 8.7);
INSERT INTO KETQUA VALUES ('002', 'C1', 5.7);
INSERT INTO KETQUA VALUES ('002', 'C2', 5.6);
INSERT INTO KETQUA VALUES ('003', 'C1', 9.0);
INSERT INTO KETQUA VALUES ('003', 'L1', 9.1);
INSERT INTO KETQUA VALUES ('004', 'Q1', 7.3);
INSERT INTO KETQUA VALUES ('004', 'K1', 6.6);
INSERT INTO KETQUA VALUES ('005', 'K1', 8.3);
INSERT INTO KETQUA VALUES ('006', 'C1', 4.6);
INSERT INTO KETQUA VALUES ('006', 'C2', 6.3);
INSERT INTO KETQUA VALUES ('007', 'Q1', 7.4);
INSERT INTO KETQUA VALUES ('008', 'K1', 4.4);

COMMIT;

PROMPT ===== CAC CAU TRUY VAN THUC HANH =====

-- Cau 1: Liet ke ma sinh vien, ho sinh vien, ten sinh vien, ngay sinh cua tat ca sinh vien.
SELECT MASV, HOSV, TENSV, NGAYSINH
FROM   DMSV;

-- Cau 2: Liet ke sinh vien thuoc khoa Cong nghe thong tin.
SELECT SV.MASV, SV.HOSV, SV.TENSV, KH.TENKHOA
FROM   DMSV SV
JOIN   DMKHOA KH ON SV.MAKH = KH.MAKHOA
WHERE  KH.MAKHOA = 'CN';

-- Cau 3: Liet ke sinh vien co hoc bong.
SELECT MASV, HOSV, TENSV, HOCBONG
FROM   DMSV
WHERE  HOCBONG IS NOT NULL
ORDER BY HOCBONG DESC;

-- Cau 4: Cho biet sinh vien co noi sinh o Da Nang.
SELECT MASV, HOSV, TENSV, NOISINH
FROM   DMSV
WHERE  UPPER(NOISINH) = UPPER(N'Da Nang');

-- Cau 5: Liet ke cac mon hoc co so tiet tu 45 tro len.
SELECT MAMH, TENMH, SOTIET
FROM   DMMH
WHERE  SOTIET >= 45;

-- Cau 6: Cho biet diem cua tung sinh vien theo tung mon hoc.
SELECT SV.MASV, SV.HOSV, SV.TENSV, MH.TENMH, KQ.DIEM
FROM   KETQUA KQ
JOIN   DMSV SV ON KQ.MASV = SV.MASV
JOIN   DMMH MH ON KQ.MAMH = MH.MAMH
ORDER BY SV.MASV, MH.MAMH;

-- Cau 7: Liet ke sinh vien co diem mon Co so du lieu lon hon 7.
SELECT SV.MASV, SV.HOSV, SV.TENSV, KQ.DIEM
FROM   KETQUA KQ
JOIN   DMSV SV ON KQ.MASV = SV.MASV
WHERE  KQ.MAMH = 'C1'
AND    KQ.DIEM > 7;

-- Cau 8: Tinh diem trung binh cua moi sinh vien.
SELECT SV.MASV, SV.HOSV, SV.TENSV, ROUND(AVG(KQ.DIEM), 2) AS DIEM_TRUNG_BINH
FROM   DMSV SV
JOIN   KETQUA KQ ON SV.MASV = KQ.MASV
GROUP BY SV.MASV, SV.HOSV, SV.TENSV
ORDER BY DIEM_TRUNG_BINH DESC;

-- Cau 9: Cho biet sinh vien co diem trung binh cao nhat.
SELECT *
FROM (
    SELECT SV.MASV, SV.HOSV, SV.TENSV, ROUND(AVG(KQ.DIEM), 2) AS DIEM_TRUNG_BINH
    FROM   DMSV SV
    JOIN   KETQUA KQ ON SV.MASV = KQ.MASV
    GROUP BY SV.MASV, SV.HOSV, SV.TENSV
    ORDER BY DIEM_TRUNG_BINH DESC
)
WHERE ROWNUM = 1;

-- Cau 10: Dem so luong sinh vien cua tung khoa.
SELECT KH.MAKHOA, KH.TENKHOA, COUNT(SV.MASV) AS SO_LUONG_SINH_VIEN
FROM   DMKHOA KH
LEFT JOIN DMSV SV ON KH.MAKHOA = SV.MAKH
GROUP BY KH.MAKHOA, KH.TENKHOA
ORDER BY KH.MAKHOA;

-- Cau 11: Tinh diem trung binh cua tung mon hoc.
SELECT MH.MAMH, MH.TENMH, ROUND(AVG(KQ.DIEM), 2) AS DIEM_TB_MON
FROM   DMMH MH
LEFT JOIN KETQUA KQ ON MH.MAMH = KQ.MAMH
GROUP BY MH.MAMH, MH.TENMH
ORDER BY MH.MAMH;

-- Cau 12: Liet ke cac sinh vien co diem duoi 5.
SELECT SV.MASV, SV.HOSV, SV.TENSV, MH.TENMH, KQ.DIEM
FROM   KETQUA KQ
JOIN   DMSV SV ON KQ.MASV = SV.MASV
JOIN   DMMH MH ON KQ.MAMH = MH.MAMH
WHERE  KQ.DIEM < 5
ORDER BY KQ.DIEM ASC;

-- Cau 13: Liet ke cac sinh vien hoc tu 2 mon tro len.
SELECT SV.MASV, SV.HOSV, SV.TENSV, COUNT(*) AS SO_MON
FROM   DMSV SV
JOIN   KETQUA KQ ON SV.MASV = KQ.MASV
GROUP BY SV.MASV, SV.HOSV, SV.TENSV
HAVING COUNT(*) >= 2
ORDER BY SO_MON DESC, SV.MASV;

-- Cau 14: Cho biet mon hoc co nhieu sinh vien hoc nhat.
SELECT *
FROM (
    SELECT MH.MAMH, MH.TENMH, COUNT(KQ.MASV) AS SO_SV
    FROM   DMMH MH
    LEFT JOIN KETQUA KQ ON MH.MAMH = KQ.MAMH
    GROUP BY MH.MAMH, MH.TENMH
    ORDER BY SO_SV DESC, MH.MAMH
)
WHERE ROWNUM = 1;

-- Cau 15: Liet ke sinh vien co diem cao hon diem trung binh cua toan bo bang ket qua.
SELECT SV.MASV, SV.HOSV, SV.TENSV, MH.TENMH, KQ.DIEM
FROM   KETQUA KQ
JOIN   DMSV SV ON KQ.MASV = SV.MASV
JOIN   DMMH MH ON KQ.MAMH = MH.MAMH
WHERE  KQ.DIEM > (SELECT AVG(DIEM) FROM KETQUA)
ORDER BY KQ.DIEM DESC;

-- Cau 16: Cap nhat hoc bong them 100000 cho sinh vien co diem trung binh tu 8 tro len.
UPDATE DMSV SV
SET    HOCBONG = NVL(HOCBONG, 0) + 100000
WHERE  SV.MASV IN (
           SELECT KQ.MASV
           FROM   KETQUA KQ
           GROUP BY KQ.MASV
           HAVING AVG(KQ.DIEM) >= 8
       );

COMMIT;

-- Cau 17: Liet ke hoc bong cua sinh vien sau khi cap nhat.
SELECT MASV, HOSV, TENSV, HOCBONG
FROM   DMSV
ORDER BY MASV;

-- Cau 18: Xoa cac ket qua co diem duoi 4.5.
DELETE FROM KETQUA
WHERE  DIEM < 4.5;

COMMIT;

-- Cau 19: Liet ke danh sach ket qua con lai sau khi xoa.
SELECT MASV, MAMH, DIEM
FROM   KETQUA
ORDER BY MASV, MAMH;

-- Cau 20: Liet ke sinh vien chua co ket qua mon hoc nao.
SELECT SV.MASV, SV.HOSV, SV.TENSV
FROM   DMSV SV
WHERE NOT EXISTS (
    SELECT 1
    FROM   KETQUA KQ
    WHERE  KQ.MASV = SV.MASV
);
