-- QUAN LY DE AN CONG TY
-- Da sua theo dung ten bang yeu cau: NHANVIEN, PHONGBAN, DIADIEM_PHG, DEAN, PHANCONG, THANNHAN.

SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

PROMPT ===== QUAN LY DE AN CONG TY - DROP OLD OBJECTS =====

BEGIN EXECUTE IMMEDIATE 'DROP TABLE THANNHAN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PHANCONG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DEAN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DIADIEM_PHG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE NHANVIEN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PHONGBAN CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

PROMPT ===== CREATE TABLES =====

CREATE TABLE PHONGBAN (
    MAPHG        NUMBER(2) CONSTRAINT PK_PHONGBAN PRIMARY KEY,
    TENPHG       NVARCHAR2(30) NOT NULL,
    TRPHG        CHAR(9),
    NG_NHANCHUC  DATE
);

CREATE TABLE NHANVIEN (
    MANV      CHAR(9) CONSTRAINT PK_NHANVIEN PRIMARY KEY,
    HONV      NVARCHAR2(15) NOT NULL,
    TENLOT    NVARCHAR2(15),
    TENNV     NVARCHAR2(15) NOT NULL,
    NGSINH    DATE,
    DCHI      NVARCHAR2(100),
    PHAI      NVARCHAR2(3),
    LUONG     NUMBER(12,0),
    MA_NQL    CHAR(9),
    PHG       NUMBER(2),
    CONSTRAINT FK_NV_NQL FOREIGN KEY (MA_NQL) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_NV_PHG FOREIGN KEY (PHG) REFERENCES PHONGBAN(MAPHG)
);

ALTER TABLE PHONGBAN
    ADD CONSTRAINT FK_PHONGBAN_TRPHG
    FOREIGN KEY (TRPHG) REFERENCES NHANVIEN(MANV);

CREATE TABLE DIADIEM_PHG (
    MAPHG      NUMBER(2) NOT NULL,
    DIADIEM    NVARCHAR2(30) NOT NULL,
    CONSTRAINT PK_DIADIEM_PHG PRIMARY KEY (MAPHG, DIADIEM),
    CONSTRAINT FK_DD_PHG FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
);

CREATE TABLE DEAN (
    MADA        NUMBER(3) CONSTRAINT PK_DEAN PRIMARY KEY,
    TENDA       NVARCHAR2(50) NOT NULL,
    DDIEM_DA    NVARCHAR2(30),
    PHONG       NUMBER(2) NOT NULL,
    CONSTRAINT FK_DEAN_PHONG FOREIGN KEY (PHONG) REFERENCES PHONGBAN(MAPHG)
);

CREATE TABLE PHANCONG (
    MA_NVIEN   CHAR(9) NOT NULL,
    SODA       NUMBER(3) NOT NULL,
    THOIGIAN   NUMBER(5,1) NOT NULL,
    CONSTRAINT PK_PHANCONG PRIMARY KEY (MA_NVIEN, SODA),
    CONSTRAINT FK_PC_NV FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV),
    CONSTRAINT FK_PC_DA FOREIGN KEY (SODA) REFERENCES DEAN(MADA)
);

CREATE TABLE THANNHAN (
    MA_NVIEN    CHAR(9) NOT NULL,
    TENTN       NVARCHAR2(30) NOT NULL,
    PHAI        NVARCHAR2(3),
    NGSINH      DATE,
    QUANHE      NVARCHAR2(20),
    CONSTRAINT PK_THANNHAN PRIMARY KEY (MA_NVIEN, TENTN),
    CONSTRAINT FK_TN_NV FOREIGN KEY (MA_NVIEN) REFERENCES NHANVIEN(MANV)
);

PROMPT ===== INSERT SAMPLE DATA =====

INSERT INTO PHONGBAN (MAPHG, TENPHG, TRPHG, NG_NHANCHUC) VALUES (1, N'Quan ly',       NULL, TO_DATE('01/01/2020','DD/MM/YYYY'));
INSERT INTO PHONGBAN (MAPHG, TENPHG, TRPHG, NG_NHANCHUC) VALUES (4, N'Dieu hanh',      NULL, TO_DATE('15/03/2021','DD/MM/YYYY'));
INSERT INTO PHONGBAN (MAPHG, TENPHG, TRPHG, NG_NHANCHUC) VALUES (5, N'Nghien cuu',     NULL, TO_DATE('10/06/2021','DD/MM/YYYY'));

INSERT INTO NHANVIEN VALUES ('123456789', N'Dinh',   N'Ba',    N'Tien',  TO_DATE('09/01/1980','DD/MM/YYYY'), N'Ha Noi',       N'Nam', 30000000, NULL,        5);
INSERT INTO NHANVIEN VALUES ('333445555', N'Nguyen', N'Thanh', N'Tung',  TO_DATE('08/12/1975','DD/MM/YYYY'), N'TP HCM',       N'Nam', 40000000, '123456789', 5);
INSERT INTO NHANVIEN VALUES ('999887777', N'Bui',    N'Thi',   N'Hang',  TO_DATE('19/07/1985','DD/MM/YYYY'), N'Da Nang',      N'Nu',  25000000, '333445555', 4);
INSERT INTO NHANVIEN VALUES ('987654321', N'Le',     N'Quynh', N'Nhu',   TO_DATE('20/06/1988','DD/MM/YYYY'), N'Hue',          N'Nu',  43000000, '333445555', 4);
INSERT INTO NHANVIEN VALUES ('666884444', N'Tran',   N'Van',   N'Nam',   TO_DATE('15/09/1982','DD/MM/YYYY'), N'Quang Nam',    N'Nam', 38000000, '333445555', 5);
INSERT INTO NHANVIEN VALUES ('453453453', N'Pham',   N'Kim',   N'Dung',  TO_DATE('31/07/1990','DD/MM/YYYY'), N'Quang Ngai',   N'Nu',  22000000, '987654321', 4);
INSERT INTO NHANVIEN VALUES ('987987987', N'Vo',     N'Minh',  N'Quan',  TO_DATE('29/03/1992','DD/MM/YYYY'), N'Da Nang',      N'Nam', 18000000, '987654321', 4);
INSERT INTO NHANVIEN VALUES ('888665555', N'Hoang',  N'Thi',   N'Lan',   TO_DATE('30/11/1987','DD/MM/YYYY'), N'TP HCM',       N'Nu',  35000000, '333445555', 1);

UPDATE PHONGBAN SET TRPHG = '888665555' WHERE MAPHG = 1;
UPDATE PHONGBAN SET TRPHG = '987654321' WHERE MAPHG = 4;
UPDATE PHONGBAN SET TRPHG = '333445555' WHERE MAPHG = 5;

INSERT INTO DIADIEM_PHG VALUES (1, N'TP HCM');
INSERT INTO DIADIEM_PHG VALUES (4, N'Ha Noi');
INSERT INTO DIADIEM_PHG VALUES (4, N'Da Nang');
INSERT INTO DIADIEM_PHG VALUES (5, N'TP HCM');
INSERT INTO DIADIEM_PHG VALUES (5, N'Nha Trang');

INSERT INTO DEAN VALUES (1,  N'San pham X',          N'Vung Tau',   5);
INSERT INTO DEAN VALUES (2,  N'San pham Y',          N'Nha Trang',  5);
INSERT INTO DEAN VALUES (3,  N'San pham Z',          N'TP HCM',     5);
INSERT INTO DEAN VALUES (10, N'Tin hoc hoa',         N'Ha Noi',     4);
INSERT INTO DEAN VALUES (20, N'Tai to chuc',         N'TP HCM',     1);
INSERT INTO DEAN VALUES (30, N'Phuc loi',            N'Da Nang',    4);

INSERT INTO PHANCONG VALUES ('123456789', 1, 32.5);
INSERT INTO PHANCONG VALUES ('123456789', 2,  7.5);
INSERT INTO PHANCONG VALUES ('666884444', 3, 40.0);
INSERT INTO PHANCONG VALUES ('453453453', 1, 20.0);
INSERT INTO PHANCONG VALUES ('453453453', 2, 20.0);
INSERT INTO PHANCONG VALUES ('333445555', 2, 10.0);
INSERT INTO PHANCONG VALUES ('333445555', 3, 10.0);
INSERT INTO PHANCONG VALUES ('333445555', 10, 10.0);
INSERT INTO PHANCONG VALUES ('333445555', 20, 10.0);
INSERT INTO PHANCONG VALUES ('999887777', 30, 30.0);
INSERT INTO PHANCONG VALUES ('999887777', 10, 10.0);
INSERT INTO PHANCONG VALUES ('987987987', 10, 35.0);
INSERT INTO PHANCONG VALUES ('987987987', 30,  5.0);
INSERT INTO PHANCONG VALUES ('987654321', 30, 20.0);
INSERT INTO PHANCONG VALUES ('987654321', 20, 15.0);
INSERT INTO PHANCONG VALUES ('888665555', 20, NULL);

UPDATE PHANCONG SET THOIGIAN = 0 WHERE THOIGIAN IS NULL;

INSERT INTO THANNHAN VALUES ('333445555', N'Ngoc',    N'Nu',  TO_DATE('05/04/2005','DD/MM/YYYY'), N'Con gai');
INSERT INTO THANNHAN VALUES ('333445555', N'Khang',   N'Nam', TO_DATE('25/10/2008','DD/MM/YYYY'), N'Con trai');
INSERT INTO THANNHAN VALUES ('987654321', N'Hung',    N'Nam', TO_DATE('01/01/2010','DD/MM/YYYY'), N'Con trai');
INSERT INTO THANNHAN VALUES ('123456789', N'Lien',    N'Nu',  TO_DATE('14/02/1982','DD/MM/YYYY'), N'Vo chong');
INSERT INTO THANNHAN VALUES ('888665555', N'Ba Tam',  N'Nu',  TO_DATE('10/10/1960','DD/MM/YYYY'), N'Me');

COMMIT;

PROMPT ===== CAC CAU TRUY VAN THUC HANH =====

-- Cau 1: Liet ke ma nhan vien, ho ten nhan vien, luong cua tat ca nhan vien.
SELECT MANV, HONV || ' ' || TENLOT || ' ' || TENNV AS HOTEN, LUONG
FROM   NHANVIEN;

-- Cau 2: Liet ke nhan vien thuoc phong Nghien cuu.
SELECT NV.MANV, NV.HONV || ' ' || NV.TENLOT || ' ' || NV.TENNV AS HOTEN, PB.TENPHG
FROM   NHANVIEN NV
JOIN   PHONGBAN PB ON NV.PHG = PB.MAPHG
WHERE  PB.TENPHG = N'Nghien cuu';

-- Cau 3: Liet ke nhan vien co luong tren 30000000.
SELECT MANV, HONV || ' ' || TENLOT || ' ' || TENNV AS HOTEN, LUONG
FROM   NHANVIEN
WHERE  LUONG > 30000000
ORDER BY LUONG DESC;

-- Cau 4: Cho biet thong tin de an do phong Dieu hanh phu trach.
SELECT DA.MADA, DA.TENDA, PB.TENPHG
FROM   DEAN DA
JOIN   PHONGBAN PB ON DA.PHONG = PB.MAPHG
WHERE  PB.TENPHG = N'Dieu hanh';

-- Cau 5: Liet ke nhan vien cung voi ten nguoi quan ly cua ho.
SELECT NV.MANV,
       NV.HONV || ' ' || NV.TENLOT || ' ' || NV.TENNV AS TENNHANVIEN,
       QL.MANV AS MAQUANLY,
       QL.HONV || ' ' || QL.TENLOT || ' ' || QL.TENNV AS TENQUANLY
FROM   NHANVIEN NV
LEFT JOIN NHANVIEN QL ON NV.MA_NQL = QL.MANV
ORDER BY NV.MANV;

-- Cau 6: Liet ke de an va tong so gio phan cong cho tung de an.
SELECT DA.MADA, DA.TENDA, SUM(PC.THOIGIAN) AS TONGSOGIO
FROM   DEAN DA
LEFT JOIN PHANCONG PC ON DA.MADA = PC.SODA
GROUP BY DA.MADA, DA.TENDA
ORDER BY DA.MADA;

-- Cau 7: Liet ke nhan vien tham gia tu 2 de an tro len.
SELECT NV.MANV,
       NV.HONV || ' ' || NV.TENLOT || ' ' || NV.TENNV AS HOTEN,
       COUNT(PC.SODA) AS SODEAN
FROM   NHANVIEN NV
JOIN   PHANCONG PC ON NV.MANV = PC.MA_NVIEN
GROUP BY NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
HAVING COUNT(PC.SODA) >= 2
ORDER BY SODEAN DESC, NV.MANV;

-- Cau 8: Cho biet de an co tong so gio phan cong lon nhat.
SELECT *
FROM (
    SELECT DA.MADA, DA.TENDA, SUM(PC.THOIGIAN) AS TONGSOGIO
    FROM   DEAN DA
    JOIN   PHANCONG PC ON DA.MADA = PC.SODA
    GROUP BY DA.MADA, DA.TENDA
    ORDER BY TONGSOGIO DESC
)
WHERE ROWNUM = 1;

-- Cau 9: Liet ke nhan vien dang tham gia de an San pham X.
SELECT NV.MANV,
       NV.HONV || ' ' || NV.TENLOT || ' ' || NV.TENNV AS HOTEN,
       PC.THOIGIAN
FROM   PHANCONG PC
JOIN   NHANVIEN NV ON PC.MA_NVIEN = NV.MANV
JOIN   DEAN DA ON PC.SODA = DA.MADA
WHERE  DA.TENDA = N'San pham X';

-- Cau 10: Tinh luong trung binh cua tung phong ban.
SELECT PB.MAPHG, PB.TENPHG, ROUND(AVG(NV.LUONG), 2) AS LUONGTB
FROM   PHONGBAN PB
LEFT JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.MAPHG, PB.TENPHG
ORDER BY PB.MAPHG;

-- Cau 11: Liet ke nhan vien co luong cao hon muc luong trung binh cua cong ty.
SELECT MANV, HONV || ' ' || TENLOT || ' ' || TENNV AS HOTEN, LUONG
FROM   NHANVIEN
WHERE  LUONG > (SELECT AVG(LUONG) FROM NHANVIEN)
ORDER BY LUONG DESC;

-- Cau 12: Liet ke phong ban co it nhan vien hon 2 nguoi.
SELECT PB.MAPHG, PB.TENPHG, COUNT(NV.MANV) AS SONHANVIEN
FROM   PHONGBAN PB
LEFT JOIN NHANVIEN NV ON PB.MAPHG = NV.PHG
GROUP BY PB.MAPHG, PB.TENPHG
HAVING COUNT(NV.MANV) < 2
ORDER BY PB.MAPHG;

-- Cau 13: Liet ke nhan vien khong tham gia de an nao.
SELECT NV.MANV, NV.HONV || ' ' || NV.TENLOT || ' ' || NV.TENNV AS HOTEN
FROM   NHANVIEN NV
WHERE NOT EXISTS (
    SELECT 1
    FROM   PHANCONG PC
    WHERE  PC.MA_NVIEN = NV.MANV
);

-- Cau 14: Liet ke de an duoc thuc hien tai TP HCM.
SELECT MADA, TENDA, DDIEM_DA
FROM   DEAN
WHERE  UPPER(DDIEM_DA) = UPPER(N'TP HCM');

-- Cau 15: Tang luong 10% cho nhan vien thuoc phong Quan ly.
UPDATE NHANVIEN
SET    LUONG = LUONG * 1.10
WHERE  PHG = 1;

COMMIT;

-- Cau 16: Liet ke bang luong sau khi cap nhat.
SELECT MANV, HONV || ' ' || TENLOT || ' ' || TENNV AS HOTEN, PHG, LUONG
FROM   NHANVIEN
ORDER BY MANV;

-- Cau 17: Xoa phan cong cua nhan vien 987987987 khoi de an 30.
DELETE FROM PHANCONG
WHERE  MA_NVIEN = '987987987'
AND    SODA = 30;

COMMIT;

-- Cau 18: Liet ke danh sach phan cong hien tai.
SELECT MA_NVIEN, SODA, THOIGIAN
FROM   PHANCONG
ORDER BY SODA, MA_NVIEN;

-- Cau 19: Liet ke phong ban chu tri nhieu de an nhat.
SELECT *
FROM (
    SELECT PB.MAPHG, PB.TENPHG, COUNT(DA.MADA) AS SODEAN
    FROM   PHONGBAN PB
    LEFT JOIN DEAN DA ON PB.MAPHG = DA.PHONG
    GROUP BY PB.MAPHG, PB.TENPHG
    ORDER BY SODEAN DESC, PB.MAPHG
)
WHERE ROWNUM = 1;

-- Cau 20: Liet ke nhan vien co tong so gio tham gia de an lon hon 30 gio.
SELECT NV.MANV,
       NV.HONV || ' ' || NV.TENLOT || ' ' || NV.TENNV AS HOTEN,
       SUM(PC.THOIGIAN) AS TONGGIO
FROM   NHANVIEN NV
JOIN   PHANCONG PC ON NV.MANV = PC.MA_NVIEN
GROUP BY NV.MANV, NV.HONV, NV.TENLOT, NV.TENNV
HAVING SUM(PC.THOIGIAN) > 30
ORDER BY TONGGIO DESC;
