CREATE TABLE DMKHOA (
    MAKHOA   CHAR(2) CONSTRAINT PK_DMKHOA PRIMARY KEY,
    TENKHOA  NVARCHAR2(30) NOT NULL
);

CREATE TABLE DMMH (
    MAMH     CHAR(2) CONSTRAINT PK_DMMH PRIMARY KEY,
    TENMH    NVARCHAR2(35) NOT NULL,
    SOTIET   NUMBER(3) NOT NULL
);

CREATE TABLE DMSV (
    MASV      CHAR(3) CONSTRAINT PK_DMSV PRIMARY KEY,
    HOSV      NVARCHAR2(30) NOT NULL,
    TENSV     NVARCHAR2(10) NOT NULL,
    PHAI      NVARCHAR2(3),
    NGAYSINH  DATE NOT NULL,
    NOISINH   NVARCHAR2(25),
    MAKH      CHAR(2) NOT NULL,
    HOCBONG   NUMBER(10,0),
    CONSTRAINT FK_DMSV_DMKHOA FOREIGN KEY (MAKH) REFERENCES DMKHOA(MAKHOA)
);

CREATE TABLE KETQUA (
    MASV      CHAR(3) NOT NULL,
    MAMH      CHAR(2) NOT NULL,
    DIEM      NUMBER(4,2) CHECK (DIEM BETWEEN 0 AND 10),
    CONSTRAINT PK_KETQUA PRIMARY KEY (MASV, MAMH),
    CONSTRAINT FK_KETQUA_DMSV FOREIGN KEY (MASV) REFERENCES DMSV(MASV),
    CONSTRAINT FK_KETQUA_DMMH FOREIGN KEY (MAMH) REFERENCES DMMH(MAMH)
);



INSERT INTO DMKHOA VALUES ('CN', N'Cong nghe thong tin');
INSERT INTO DMKHOA VALUES ('QT', N'Quan tri kinh doanh');
INSERT INTO DMKHOA VALUES ('KT', N'Ke toan');

INSERT INTO DMMH VALUES ('C1', N'Co so du lieu', 45);
INSERT INTO DMMH VALUES ('C2', N'Cau truc du lieu', 45);
INSERT INTO DMMH VALUES ('L1', N'Lap trinh huong doi tuong', 60);
INSERT INTO DMMH VALUES ('K1', N'Ke toan tai chinh', 30);
INSERT INTO DMMH VALUES ('Q1', N'Nhap mon quan tri', 30);

INSERT INTO DMSV VALUES ('001', N'Nguyen', N'An',    N'Nam', TO_DATE('12/03/2005','DD/MM/YYYY'), N'Da Nang',   'CN', 500000);
INSERT INTO DMSV VALUES ('002', N'Tran',   N'Binh',  N'Nam', TO_DATE('25/07/2005','DD/MM/YYYY'), N'Hue',       'CN', NULL);
INSERT INTO DMSV VALUES ('003', N'Le',     N'Chi',   N'Nu',  TO_DATE('09/09/2005','DD/MM/YYYY'), N'Da Nang',   'CN', 300000);
INSERT INTO DMSV VALUES ('004', N'Pham',   N'Dung',  N'Nu',  TO_DATE('01/01/2005','DD/MM/YYYY'), N'Quang Nam', 'QT', NULL);
INSERT INTO DMSV VALUES ('005', N'Vo',     N'Em',    N'Nu',  TO_DATE('18/11/2005','DD/MM/YYYY'), N'Da Nang',   'KT', 200000);
INSERT INTO DMSV VALUES ('006', N'Hoang',  N'Giang', N'Nam', TO_DATE('22/04/2005','DD/MM/YYYY'), N'Quang Tri', 'CN', NULL);
INSERT INTO DMSV VALUES ('007', N'Bui',    N'Hanh',  N'Nu',  TO_DATE('30/05/2005','DD/MM/YYYY'), N'Hue',       'QT', 400000);
INSERT INTO DMSV VALUES ('008', N'Dang',   N'Khoa',  N'Nam', TO_DATE('14/02/2005','DD/MM/YYYY'), N'Da Nang',   'KT', NULL);

INSERT INTO KETQUA VALUES ('001', 'C1', 7.7);
INSERT INTO KETQUA VALUES ('001', 'C2', 7.8);
INSERT INTO KETQUA VALUES ('001', 'L1', 8.7);
INSERT INTO KETQUA VALUES ('002', 'C1', 5.7);
INSERT INTO KETQUA VALUES ('002', 'C2', 5.6);
INSERT INTO KETQUA VALUES ('003', 'C1', 9.0);
INSERT INTO KETQUA VALUES ('003', 'L1', 9.1);
INSERT INTO KETQUA VALUES ('004', 'Q1', 7.3);
INSERT INTO KETQUA VALUES ('004', 'K1', 6.6);
INSERT INTO KETQUA VALUES ('005', 'K1', 8.3);
INSERT INTO KETQUA VALUES ('006', 'C1', 4.6);
INSERT INTO KETQUA VALUES ('006', 'C2', 6.3);
INSERT INTO KETQUA VALUES ('007', 'Q1', 7.4);
INSERT INTO KETQUA VALUES ('008', 'K1', 4.4);

COMMIT;

