----tạo user---
CREATE USER tranthithanhthao_buoi4 IDENTIFIED by 123;

---cấp quyền login cho user---
GRANT CREATE SESSION, CREATE TABLE TO tranthithanhthao_buoi4;

---cấp quyền 
ALTER USER tranthithanhthao_buoi4 QUOTA UNLIMITED ON USERS;

CREATE USER BAITHI2 IDENTIFIED BY 123;

GRANT CONNECT, RESOURCE, CREATE TRIGGER TO BAITHI2;

ALTER USER BAITHI2 QUOTA UNLIMITED ON USERS;

CONNECT BAITHI2/123;

GRANT CONNECT, RESOURCE, CREATE TRIGGER TO BAITHI2;
ALTER USER BAITHI2 QUOTA UNLIMITED ON USERS;

CREATE USER nguyenvanb IDENTIFIED by 123;
---cấp quyền login cho user---
GRANT CREATE SESSION, CREATE TABLE TO tranthithanhthao;
GRANT CREATE SESSION, CREATE TABLE TO nguyenvanb;
---cấp quyền 
ALTER USER tranthithanhthao QUOTA UNLIMITED ON USERS;
ALTER USER nguyenvanb QUOTA UNLIMITED ON USERS;
----CDB(máy chủ): database cha, PDB(website/app): database con----
SHOW CON_NAME;
SHOW PDBS;
ALTER SESSION SET CONTAINER = XEPDB1;

----buoi7
CREATE USER tranthithanhthao_buoi7 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO tranthithanhthao_buoi7;
ALTER USER tranthithanhthao_buoi7 QUOTA UNLIMITED ON USERS;
----buoi8
CREATE USER tranthithanhthao_buoi8 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO tranthithanhthao_buoi8;
ALTER USER tranthithanhthao_buoi8 QUOTA UNLIMITED ON USERS;

---buoi9
CREATE USER tranthithanhthao_buoi9 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO tranthithanhthao_buoi9;
ALTER USER tranthithanhthao_buoi8 QUOTA UNLIMITED ON USERS;

CREATE USER tranthithanhthao_b9_bt1 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO tranthithanhthao_b9_bt1;
ALTER USER tranthithanhthao_b9_bt1 QUOTA UNLIMITED ON USERS;

CREATE USER tranthithanhthao_b9_bt2 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO tranthithanhthao_b9_bt2;
ALTER USER tranthithanhthao_b9_bt2 QUOTA UNLIMITED ON USERS;
---buoi10
CREATE USER tranthithanhthao_b10_QLBanHang IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO tranthithanhthao_b10_QLBanHang;
ALTER USER tranthithanhthao_b10_QLBanHang QUOTA UNLIMITED ON USERS;

CREATE USER tranthithanhthao_b10_QL_KHACHSAN IDENTIFIED BY 123;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,CREATE TRIGGER, CREATE PROCEDURE TO tranthithanhthao_b10_QL_KHACHSAN;
ALTER USER tranthithanhthao_b10_QL_KHACHSAN QUOTA UNLIMITED ON USERS;

CREATE USER Tuan2_1250080179 IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO Tuan2_1250080179;
ALTER USER Tuan2_1250080179 QUOTA UNLIMITED ON USERS;

CREATE USER Tuan2_1250080179_QL_DSV IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO Tuan2_1250080179_QL_DSV;
ALTER USER Tuan2_1250080179_QL_DSV QUOTA UNLIMITED ON USERS;

CREATE USER Tuan2_1250080179_QL_DACTY IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO Tuan2_1250080179_QL_DACTY;
ALTER USER Tuan2_1250080179_QL_DACTY QUOTA UNLIMITED ON USERS;

CREATE USER Tuan3_1250080179_QL_SV IDENTIFIED BY 123;
GRANT DBA TO Tuan3_1250080179_QL_SV;
ALTER USER Tuan3_1250080179_QL_SV QUOTA UNLIMITED ON USERS;

ALTER SESSION SET CONTAINER = XEPDB1;

ALTER SYSTEM KILL SESSION '1594,51377' IMMEDIATE;
----th1
SHOW PDBS;
ALTER SESSION SET CONTAINER = XEPDB1;
CREATE USER tranthithanhthao_th1 IDENTIFIED BY 123;
GRANT DBA TO tranthithanhthao_th1;
---xem user không cần quyền----
SELECT username
FROM dba_users
WHERE username IN ('TRANTHITHANHTHAO', 'NGUYENVANB');
---xem user ở PDB con hiện tại---
SELECT username
FROM dba_users
WHERE username NOT LIKE 'C##%';
---xem tất cả user trong PDB hiện tại---
SELECT username
FROM dba_users
ORDER BY username;
---tạo bảng---


---buoi1
CREATE USER tranthithanhthao IDENTIFIED BY 123;
GRANT CONNECT, RESOURCE, CREATE TRIGGER TO tranthithanhthao ;
ALTER USER tranthithanhthao  QUOTA UNLIMITED ON USERS;

