CREATE TABLE SACH (
    MASACH VARCHAR2(10) PRIMARY KEY,
    TENSACH NVARCHAR2(200) NOT NULL,
    MATG VARCHAR2(10),
    MANXB VARCHAR2(10),
    NAMXB NUMBER
);
CREATE TABLE MONHOC (
    MAMH VARCHAR2(10) PRIMARY KEY,
    TENMH NVARCHAR2(100) NOT NULL,
    SOTINCHI NUMBER
);
CREATE TABLE LOP (
    MALOP VARCHAR2(20) PRIMARY KEY,
    TENLOP NVARCHAR2(100),
    KHOA NVARCHAR2(100)
);
INSERT INTO LOP(MALOP, TENLOP, KHOA)
VALUES ('L001', N'12_ĐH_CNTT4', 'K12');
---trao quyền chỉnh sửa cho user tranthithanhthao---
GRANT UPDATE
ON LOP
TO tranthithanhthao;

INSERT INTO tranthithanhthao.TACGIA VALUES('TG003',N'Nguyen B');
COMMIT;


