CREATE TABLE HANGHANGKHONG (
    MAHANG VARCHAR2(10) PRIMARY KEY,
    TENHANG VARCHAR2(100),
    NGTL DATE,
    DUONGBAY NUMBER
);

CREATE TABLE CHUYENBAY (
    MACB VARCHAR2(10) PRIMARY KEY,
    MAHANG VARCHAR2(10),
    XUATPHAT VARCHAR2(50),
    DIEMDEN VARCHAR2(50),
    BATDAU DATE,
    TGBAY NUMBER,
    CONSTRAINT FK_CB_HHK FOREIGN KEY (MAHANG)
        REFERENCES HANGHANGKHONG(MAHANG)
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    GIOITINH VARCHAR2(10),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR2(50),
    CONSTRAINT CK_CHUYENMON 
        CHECK (CHUYENMON IN ('Phi công', 'Tiếp viên'))
);

CREATE TABLE PHANCONG (
    MACB VARCHAR2(10),
    MANV VARCHAR2(10),
    NHIEMVU VARCHAR2(50),
    CONSTRAINT PK_PC PRIMARY KEY (MACB, MANV),
    CONSTRAINT FK_PC_CB FOREIGN KEY (MACB)
        REFERENCES CHUYENBAY(MACB),
    CONSTRAINT FK_PC_NV FOREIGN KEY (MANV)
        REFERENCES NHANVIEN(MANV)
);

-- HANGHANGKHONG
INSERT INTO HANGHANGKHONG VALUES ('VN', 'Vietnam Airlines', DATE '1956-01-15', 52);
INSERT INTO HANGHANGKHONG VALUES ('VJ', 'Vietjet Air', DATE '2011-12-25', 33);
INSERT INTO HANGHANGKHONG VALUES ('BL', 'Jetstar Pacific Airlines', DATE '1990-12-01', 13);

-- CHUYENBAY
INSERT INTO CHUYENBAY VALUES ('VN550', 'VN', 'TP.HCM', 'Singapore', 
    TO_DATE('20/12/2025 13:15','DD/MM/YYYY HH24:MI'), 2);

INSERT INTO CHUYENBAY VALUES ('VJ331', 'VJ', 'Đà Nẵng', 'Vinh', 
    TO_DATE('28/12/2025 22:30','DD/MM/YYYY HH24:MI'), 1);

INSERT INTO CHUYENBAY VALUES ('BL696', 'BL', 'TP.HCM', 'Đà Lạt', 
    TO_DATE('24/12/2025 06:00','DD/MM/YYYY HH24:MI'), 0.5);

-- NHANVIEN
INSERT INTO NHANVIEN VALUES ('NV01','Lâm Văn Bền','Nam',
    DATE '1991-09-10', DATE '2021-06-05','Phi công');

INSERT INTO NHANVIEN VALUES ('NV02','Dương Thị Lục','Nữ',
    DATE '1989-03-22', DATE '2020-11-12','Tiếp viên');

INSERT INTO NHANVIEN VALUES ('NV03','Hoàng Thanh Tùng','Nam',
    DATE '1995-07-29', DATE '2022-04-11','Tiếp viên');

-- PHANCONG
INSERT INTO PHANCONG VALUES ('VN550','NV01','Cơ trưởng');
INSERT INTO PHANCONG VALUES ('VN550','NV02','Tiếp viên');
INSERT INTO PHANCONG VALUES ('BL696','NV03','Tiếp viên trưởng');

--Câu 4. Hiện thực ràng buộc toàn vẹn sau: Ngày bắt đầu chuyến bay luôn lớn hơn ngày thành lập hãng  hàng không quản lý chuyến bay đó. 
CREATE OR REPLACE TRIGGER TRG_CHECK_NGAY
BEFORE INSERT OR UPDATE ON CHUYENBAY
FOR EACH ROW
DECLARE
    v_ngtl DATE;
BEGIN
    SELECT NGTL INTO v_ngtl
    FROM HANGHANGKHONG
    WHERE MAHANG = :NEW.MAHANG;

    IF :NEW.BATDAU <= v_ngtl THEN
        RAISE_APPLICATION_ERROR(-20001, 
        'Ngay bay phai lon hon ngay thanh lap');
    END IF;
END;
/
--Câu 5. Tìm tất cả các nhân viên có sinh nhậttrong tháng 07. 
SELECT * 
FROM NHANVIEN
WHERE EXTRACT(MONTH FROM NGSINH) = 7;
--Câu 6. Tìm chuyến bay có số nhân viên nhiều nhất. 
SELECT MACB
FROM PHANCONG
GROUP BY MACB
HAVING COUNT(*) = (
    SELECT MAX(COUNT(*))
    FROM PHANCONG
    GROUP BY MACB
);
--Câu 7. Với mỗihãng hàng không, thống kê số chuyến bay có điểm xuất phát là ‘Đà Nẵng’ và có số nhân viên được phân công ít hơn 2. 
SELECT h.MAHANG, COUNT(*) AS SOCHUYEN
FROM HANGHANGKHONG h
JOIN CHUYENBAY c ON h.MAHANG = c.MAHANG
LEFT JOIN PHANCONG p ON c.MACB = p.MACB
WHERE c.XUATPHAT = 'Đà Nẵng'
GROUP BY h.MAHANG, c.MACB
HAVING COUNT(p.MANV) < 2;
--Câu 8. Tìm nhân viên được phân công tham gia tất cả các chuyến bay.
SELECT MANV
FROM PHANCONG
GROUP BY MANV
HAVING COUNT(DISTINCT MACB) = (SELECT COUNT(*) FROM CHUYENBAY);

